---
- name:         fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register:     wp_salt
  become:       no

- name: copy WordPress config file
  template:
    src:  wp-config.php
    dest: "{{ wordpress_path }}"
