---
- name: download pngout
  get_url:
    url:  "{{ pngout_url }}"
    dest: /tmp/{{ pngout_file_name }}

- name: extract pngout
  unarchive:
    src:  /tmp/{{ pngout_file_name }}
    dest: /tmp
    copy: false

- name:    copy pngout executable to image_optim folder
  command: mv /tmp/pngout-{{ pngout_version }}-linux/x86_64/pngout {{ image_optim_directory }}
