---
- name: download nodejs {{ nodejs_version_tag }}
  get_url:
    url:  "{{ nodejs_tarball_url }}"
    dest: "{{ nodejs_temp_dir }}"

- name: create nodejs directory
  file:
    path:  "{{ nodejs_user_dir }}"
    state: directory

- name:  unpack nodejs {{ nodejs_version_tag }}
  shell: >
    tar --strip-components 1 -xzvf
    {{ nodejs_temp_dir }}
    -C {{ nodejs_user_dir }}
