---
- name:       add RHEL EPEL repository
  yum:        name={{epel_url}}
  with_items: "{{ repos_url }}"

- name:    install common packages
  package: name={{ item }}
  with_items:
    - git
    - ruby
    - epel-release
