---
- name:    install git dependencies
  package: name={{ item }}
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - perl-devel
    - zlib-devel
    - autoconf
    - gcc
