---
- name:         download ssh keys
  become:       false
  local_action: get_url
                url=https://github.com/{{ item }}.keys
                dest=/tmp/{{ item }}
  with_items: developers

- name: add ssh developers keys
  authorized_key:
    user: "{{ user_name }}"
    key:  "{{ lookup('file', '/tmp/' + item) }}"
  with_items: developers
