---
- name: create user
  user:
    name:   "{{ user_name }}"
    group:  "{{ group_name }}"
    system: yes

- name: add permissions
  file:
    path:    "{{ user_home }}"
    mode:    0755
    recurse: yes
