------
- name: install common packages
  yum:  name={{ item }}
  with_items:
    - ruby
    - zsh

- name:     check for oh-my-zsh installation
  status:   dir_path={{ user_home }}/.oh-my-zsh
  register: zsh_installation

- name:  clone ohmyzsh repo
  git:
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ user_home }}/.oh-my-zsh"
    accept_hostkey: yes
  when: not zsh_installation.exists

- name: copy .zshrc
  copy:
    src:  .zshrc
    dest: "{{ user_home }}"

- name: set zsh as default shell
  user: name={{ user_name }} shell=/bin/zsh
