---
- name: copy html template
  template: src=sites-available-static.j2 dest=/etc/nginx/sites-available/{{ webserver_name }}
  when: kind is defined and kind == 'html'

- name: copy server template
  template: src=sites-available-dynamic.j2 dest=/etc/nginx/sites-available/{{ webserver_name }}
  when: kind is defined and kind == 'server'

- name: make symlink from sites-available to sites-enabled
  file:
    src:  /etc/nginx/sites-available/{{ webserver_name }}
    dest: /etc/nginx/sites-enabled/{{ webserver_name }}
    state: link
  notify: reload nginx

- name: copy SSL certificates
  copy:
    src:  '{{ item.0 }}'
    dest: '{{ item.1 }}'
  with_together:
    - ['{{ ssl_private_path }}',               '{{ ssl_public_path }}']
    - ['/etc/ssl/private/{{ user_name }}.key', '/etc/ssl/certs/{{ user_name }}.crt']
  when: ssl | default(false)
