---
- name: copy SSL certificates
  copy:
    src:  "{{ file.0 }}"
    dest: "{{ file.1 }}"
  with_together:
    - ["{{ ssl_certs_dir }}/server.key", "{{ ssl_certs_dir }}/server.crt"]
    - ["{{ ssl_certificate_path_key }}", "{{ ssl_certificate_path_crt }}"]
  loop_control:
    loop_var: file
  when: ssl | default(false)
