---
- name: clone Certbot into configured directory.
  git:
    repo:    "{{ certbot_repo }}"
    dest:    "{{ certbot_dir }}"
    version: master
    update:  yes
    force:   yes

- name: ensure certbot-auto is executable.
  file:
    path: "{{ certbot_dir }}/certbot-auto"
    mode: 0755
