---
- hosts:        all
  gather_facts: yes
  sudo:         yes
  vars:
    user_name: api
  vars_files:
    - ../vars/developers.yml
    - ../vars/domains.yml
  roles:
    - { role: ../roles/users,   tags: ['users']   }
    - { role: ../roles/ruby,    tags: ['ruby']    }
    - { role: ../roles/rails,   tags: ['rails']   }
    - { role: ../roles/sidekiq, tags: ['sidekiq'] }
    - {
        role:         ../roles/github,
        user_ssh_key: ../files/ssh-keys/id_rsa,
        tags:         ['github']
      }
    - {
        role:      ../roles/nginx-domain,
        tags:      ['domain'],
        subdomain: api,
        kind:      server
      }
