---
- hosts:        all
  gather_facts: yes
  sudo:         yes
  vars_files:
    - ../vars/developers.yml
  roles:
    - { role: ../roles/utils,             tags: ['common', 'utils']     }
    - { role: ../roles/git,               tags: ['common', 'git']       }
    - { role: ../roles/swap,              tags: ['common', 'swap']      }
    - { role: ../roles/nginx-server,      tags: ['common', 'nginx']     }
    - { role: ../roles/postgres,          tags: ['common', 'postgres']  }
    - { role: ../roles/redis,             tags: ['common', 'redis']     }
    - { role: ../roles/mongodb,           tags: ['common', 'mongodb']   }
    - { role: ../roles/vertx,             tags: ['common', 'vertx']     }
    - { role: ../roles/authorized-access, tags: ['common', 'auth']      }
    - { role: ../roles/clojure-leiningen, tags: ['common', 'leiningen'] }

- include: api.yml
- include: website.yml
