---
- hosts:        all
  gather_facts: yes
  become:       yes
  vars:
    user_name: website
  vars_files:
    - ../vars/developers.yml
    - ../vars/domains.yml
  roles:
    - { role: ../roles/users,       tags: ['users']       }
    - { role: ../roles/ruby,        tags: ['ruby']        }
    - { role: ../roles/nodejs,      tags: ['node']        }
    - { role: ../roles/image-optim, tags: ['image-optim'] }
    - { role: ../roles/jpegoptim,   tags: ['jpegoptim']   }
    - {
        role:         ../roles/github,
        user_ssh_key: ../files/ssh-keys/id_rsa,
        tags:         ['github']
      }
    - {
        role:            ../../roles/nginx-domain,
        tags:            ['domain'],
        subdomain:       ~,
        kind:            static,
        prerender_token: 'abc123'
      }
