- name: create .bundle directory
  file:
    path: "{{ user_home }}/.bundle"
    state: directory

- name: configure bundler
  template:
    src:  config.j2
    dest: "{{ user_home }}/.bundle/config"

- name: do not download documentation with gems
  copy: src=.gemrc dest={{ user_home }}

- name: make user ruby owner
  file:
    path:    "{{ ruby_path }}"
    recurse: yes
    owner:   "{{ user_name }}"

- name:    install bundler
  command: "{{ user_home }}/ruby/bin/gem install bundler"
