---
- name: copy config template
  template:
    src:  pg_backup.config
    dest: "{{ scripts_dir }}"

- name: copy cron task script
  copy:
    src:  pg_backup.sh
    dest: "{{ scripts_dir }}"
    mode: "u+x,g+x"
