---
- name:          check for firewalld/iptables
  command:       firewall-cmd --state
  register:      firewalld
  always_run:    yes
  changed_when:  false
  ignore_errors: yes

- name:    add port rules (iptables)
  include: iptables.yml
  when:    firewalld.rc != 0

- name:    add port rules (firewalld)
  include: firewalld.yml
  when:    firewalld.rc == 0
