---
- name: set openvpn service name - systemd
  set_fact:
    openvpn_service_name: "{{ openvpn_suggested_service_name }}"
  when: ansible_service_mgr == "systemd"

- name: disable openvpn auto-start & start
  service:
    name:    "{{ openvpn_service_name }}"
    enabled: no
    state:   stopped

- name: wipe out config directory
  file:
    path:  /etc/openvpn
    state: absent

- name: remove openvpn logrotate config file
  file:
    path:  "{{ logrotate_config_file }}"
    state: absent

- name: uninstall OpenVPN
  package:
    name:  openvpn
    state: absent

